### PR TITLE
Add options page

### PR DESCRIPTION
**Pull request by bfred-it**
With this the users can access a more permanent view rather than just via popup that can close automatically.

screen shot 2017-02-13 at 01 28 42

### CODE REVIEW

**Comment by bfred-it** [comment]
How does this look?

**Comment by HangYang** [comment]
This looks good, but please check this. 
https://www.screencast.com/t/Wwklsbnq
I'm on Windows 10 64bit

**Comment by HangYang** [comment]
Also I'm having issue in the popup too. the window is expanding after taking disable/enable action. I did not notice this before and already published it.
https://www.screencast.com/t/ZwyxMlX5xyyI

**Comment by bfred-it** [comment]
hah, nice. I didn't have that issue because my scrollbars are hidden. 

I was using `width: 100vw` to force the page to be at least as big as the popup, which caused a loop.

**Comment by HangYang** [comment]
image
Ah, might need to twist the options page style a bit.

**Comment by bfred-it** [comment]
The issue is that I can't differentiate between the popup and the options, so what you see in 		9e74a60 is a hackish way to try to match the window size. Perhaps that 200ms should be increased.

**Comment by HangYang** [comment]
Oh, OK, I will see what I can do

**Pull request merged**
