### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by bfred-it**
Full list in the commits :)

### CODE REVIEW

**Comment by HangYang** [comment]
Thanks for doing this.
Since you are also contributing this extension, I'd like to remove all of my own link from the READ.ME :)

**Comment by bfred-it** [comment]
Oh don't worry about that :)

**Comment by bfred-it** [comment]
If you want though you could add me as a collaborator in the settings: https://github.com/HangYang/ext_manager/settings

**Comment by HangYang** [comment]
added

**Comment by bfred-it** [comment]
Thank you! :)

I'll still send PRs for non-minor changes

**Pull request merged**
